#!/bin/sh
### BEGIN INIT INFO
# Provides:          chrony-init
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start chronyd at boot time
# Description:       Enable service provided by chrony
### END INIT INFO

case "$1" in
  start)
    echo "Starting chronyd..."
    /usr/sbin/chronyd -d -f /etc/chrony.conf &
    ;;
  stop)
    echo "Stopping chronyd..."
    pkill -f "/usr/sbin/chronyd"
    ;;
  *)
    echo "Usage: $0 {start|stop}"
    exit 1
    ;;
esac

exit 0
