#!/bin/sh
### BEGIN INIT INFO
# Provides:          hello-kivy
# Required-Start:    $local_fs $remote_fs $syslog
# Required-Stop:     $local_fs $remote_fs $syslog
# Default-Start:     5
# Default-Stop:      0 1 6
# Short-Description: Start Kivy app on KMS/DRM
### END INIT INFO

APP=/usr/bin/hello_kivy.py
PIDFILE=/run/hello-kivy.pid

start() {
    echo "Starting hello-kivy"

    export KIVY_WINDOW=sdl2
    export SDL_VIDEODRIVER=kmsdrm
    export KIVY_NO_ARGS=1
    export KIVY_LOG_LEVEL=info

    # Optional but recommended
    export XDG_RUNTIME_DIR=/run/user/0
    mkdir -p $XDG_RUNTIME_DIR
    chmod 0700 $XDG_RUNTIME_DIR

    start-stop-daemon \
        --start \
        --background \
        --make-pidfile \
        --pidfile $PIDFILE \
        --exec /usr/bin/python3 \
        -- $APP
}

stop() {
    echo "Stopping hello-kivy"
    start-stop-daemon --stop --pidfile $PIDFILE
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0

