#!/bin/sh
### BEGIN INIT INFO
# Provides:          kivy-app
# Required-Start:    $local_fs
# Required-Stop:
# Default-Start:     5
# Default-Stop:
# Short-Description: Start Kivy app on X11
### END INIT INFO

XINIT=/usr/bin/xinit
XINITRC=/etc/X11/xinit/xinitrc-kivy

case "$1" in
  start)
    echo "Starting Kivy application..."
    $XINIT $XINITRC -- :0 vt1 &
    ;;
  stop)
    echo "Stopping Kivy application..."
    killall Xorg python3 || true
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit 0

